In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [25]:
import seaborn as sns

In [27]:
df=pd.read_csv("../data/raw/cs-training.csv")
print("Shape:", df.shape)
df.head()

Shape: (150000, 12)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [29]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,150000.0,75000.500000,43301.414527,1.0,37500.750000,75000.500000,112500.250000,150000.0
SeriousDlqin2yrs,150000.0,0.066840,0.249746,0.0,0.000000,0.000000,0.000000,1.0
RevolvingUtilizationOfUnsecuredLines,150000.0,6.048438,249.755371,0.0,0.029867,0.154181,0.559046,50708.0
age,150000.0,52.295207,14.771866,0.0,41.000000,52.000000,63.000000,109.0
NumberOfTime30-59DaysPastDueNotWorse,150000.0,0.421033,4.192781,0.0,0.000000,0.000000,0.000000,98.0
DebtRatio,150000.0,353.005076,2037.818523,0.0,0.175074,0.366508,0.868254,329664.0
MonthlyIncome,120269.0,6670.221237,14384.674215,0.0,3400.000000,5400.000000,8249.000000,3008750.0
NumberOfOpenCreditLinesAndLoans,150000.0,8.452760,5.145951,0.0,5.000000,8.000000,11.000000,58.0
NumberOfTimes90DaysLate,150000.0,0.265973,4.169304,0.0,0.000000,0.000000,0.000000,98.0
NumberRealEstateLoansOrLines,150000.0,1.018240,1.129771,0.0,0.000000,1.000000,2.000000,54.0
NumberOfTime60-89DaysPastDueNotWorse,150000.0,0.240387,4.155179,0.0,0.000000,0.000000,0.000000,98.0
NumberOfDependents,146076.0,0.757222,1.115086,0.0,0.000000,0.000000,1.000000,20.0

In [37]:
df.columns.to_list()

['Unnamed: 0',
 'SeriousDlqin2yrs',
 'RevolvingUtilizationOfUnsecuredLines',
 'age',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfDependents']

In [30]:
TARGET = "SeriousDlqin2yrs"
df[TARGET].value_counts()

SeriousDlqin2yrs
0    139974
1     10026
Name: count, dtype: int64

In [31]:
df[TARGET].value_counts(normalize=True) * 100

SeriousDlqin2yrs
0    93.316
1     6.684
Name: proportion, dtype: float64

In [32]:
# Missing values
df.isnull().sum().sort_values(ascending=False)

MonthlyIncome                           29731
NumberOfDependents                       3924
Unnamed: 0                                  0
SeriousDlqin2yrs                            0
age                                         0
RevolvingUtilizationOfUnsecuredLines        0
DebtRatio                                   0
NumberOfTime30-59DaysPastDueNotWorse        0
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
dtype: int64

In [33]:
# Duplicate rows
df.duplicated().sum()

np.int64(0)

In [34]:
# Numerical columns
df.select_dtypes(include=np.number).columns.tolist()

['Unnamed: 0',
 'SeriousDlqin2yrs',
 'RevolvingUtilizationOfUnsecuredLines',
 'age',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfDependents']

In [38]:
df.nunique().sort_values()

SeriousDlqin2yrs                             2
NumberOfDependents                          13
NumberOfTime60-89DaysPastDueNotWorse        13
NumberOfTime30-59DaysPastDueNotWorse        16
NumberOfTimes90DaysLate                     19
NumberRealEstateLoansOrLines                28
NumberOfOpenCreditLinesAndLoans             58
age                                         86
MonthlyIncome                            13594
DebtRatio                               114194
RevolvingUtilizationOfUnsecuredLines    125728
Unnamed: 0                              150000
dtype: int64

In [ ]:
df[df["age"] == 0].shape

(1, 12)

In [42]:
df[df["age"] >= 100].shape

(13, 12)

In [49]:
df[df["MonthlyIncome"] == 0].shape

(1634, 12)

In [45]:
print("30-59:", (df["NumberOfTime30-59DaysPastDueNotWorse"] == 98).sum())
print("60-89:", (df["NumberOfTime60-89DaysPastDueNotWorse"] == 98).sum())
print("90+:", (df["NumberOfTimes90DaysLate"] == 98).sum())

30-59: 264
60-89: 264
90+: 264

In [46]:
df[df["NumberOfDependents"] == 20].shape

(1, 12)

In [47]:
df["DebtRatio"].quantile([0.90, 0.95, 0.99, 0.999])

0.900     1267.000
0.950     2449.000
0.990     4979.040
0.999    10613.074
Name: DebtRatio, dtype: float64

In [48]:
df["RevolvingUtilizationOfUnsecuredLines"].quantile(
    [0.90, 0.95, 0.99, 0.999]
)

0.900       0.981278
0.950       1.000000
0.990       1.092956
0.999    1571.006000
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [50]:
df.loc[df["age"] >= 100, "age"].value_counts().sort_index()

age
101    3
102    3
103    3
105    1
107    1
109    2
Name: count, dtype: int64

In [51]:
df.loc[df["age"] >= 100, "age"].value_counts().sort_index()

age
101    3
102    3
103    3
105    1
107    1
109    2
Name: count, dtype: int64

In [53]:
df[df["MonthlyIncome"] == 0].head(10)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
14,15,0,0.019657,76,0,477.0,0.0,6,0,1,0,0.0
50,51,0,0.818978,73,0,3095.0,0.0,9,0,1,1,0.0
73,74,0,0.059669,31,0,3162.0,0.0,11,0,2,0,1.0
90,91,0,0.039388,51,0,15466.0,0.0,7,0,0,0,0.0
298,299,0,0.085152,25,0,1005.0,0.0,5,0,0,0,0.0
326,327,0,0.013115,43,0,4211.0,0.0,21,0,2,0,2.0
508,509,0,1.000000,73,0,8500.0,0.0,2,0,0,0,0.0
537,538,0,0.086635,40,0,887.0,0.0,8,0,1,0,1.0
605,606,0,0.155742,39,0,723.0,0.0,13,0,0,0,2.0
629,630,0,1.000000,40,0,2866.0,0.0,2,0,2,0,0.0

In [54]:
df[
    df["NumberOfTime30-59DaysPastDueNotWorse"] == 98
][
    [
        "NumberOfTime30-59DaysPastDueNotWorse",
        "NumberOfTime60-89DaysPastDueNotWorse",
        "NumberOfTimes90DaysLate",
        "SeriousDlqin2yrs"
    ]
].head(20)

,NumberOfTime30-59DaysPastDueNotWorse,NumberOfTime60-89DaysPastDueNotWorse,NumberOfTimes90DaysLate,SeriousDlqin2yrs
1733,98,98,98,1
2286,98,98,98,0
3884,98,98,98,0
4417,98,98,98,0
4705,98,98,98,0
5073,98,98,98,0
6280,98,98,98,1
7032,98,98,98,1
7117,98,98,98,1
7687,98,98,98,1
8173,98,98,98,1
9278,98,98,98,0
9648,98,98,98,1
9685,98,98,98,0
10201,98,98,98,0
10245,98,98,98,1
11161,98,98,98,1
11362,98,98,98,1
12021,98,98,98,0
12131,98,98,98,1

In [55]:
for col in [
    "NumberOfTime30-59DaysPastDueNotWorse",
    "NumberOfTime60-89DaysPastDueNotWorse",
    "NumberOfTimes90DaysLate"
]:
    print("\n", col)
    print(df[col].value_counts().sort_index(ascending=False).head(10))

 NumberOfTime30-59DaysPastDueNotWorse
NumberOfTime30-59DaysPastDueNotWorse
98    264
96      5
13      1
12      2
11      1
10      4
9      12
8      25
7      54
6     140
Name: count, dtype: int64

 NumberOfTime60-89DaysPastDueNotWorse
NumberOfTime60-89DaysPastDueNotWorse
98    264
96      5
11      1
9       1
8       2
7       9
6      16
5      34
4     105
3     318
Name: count, dtype: int64

 NumberOfTimes90DaysLate
NumberOfTimes90DaysLate
98    264
96      5
17      1
15      2
14      2
13      4
12      2
11      5
10      8
9      19
Name: count, dtype: int64

In [56]:
df.nlargest(
    10,
    "DebtRatio"
)[
    [
        "DebtRatio",
        "MonthlyIncome",
        "age",
        "SeriousDlqin2yrs"
    ]
]

        DebtRatio  MonthlyIncome  age  SeriousDlqin2yrs
60152    329664.0            NaN   65                 0
36600    326442.0            NaN   65                 0
127047   307001.0            NaN   58                 0
58900    220516.0            NaN   37                 0
4854     168835.0            NaN   56                 0
7513     110952.0            NaN   71                 0
103041   106885.0            NaN   65                 0
69845    101320.0            NaN   66                 0
66785     61907.0            NaN   63                 0
53682     61106.5            1.0   89                 0

In [57]:
df.nlargest(
    10,
    "RevolvingUtilizationOfUnsecuredLines"
)[
    [
        "RevolvingUtilizationOfUnsecuredLines",
        "MonthlyIncome",
        "DebtRatio",
        "SeriousDlqin2yrs"
    ]
]

,RevolvingUtilizationOfUnsecuredLines,MonthlyIncome,DebtRatio,SeriousDlqin2yrs
85489,50708.0,38000.0,0.221757,0
31414,29110.0,10000.0,0.402560,0
16956,22198.0,NaN,2312.000000,0
149160,22000.0,3973.0,1.080020,0
149279,20514.0,9902.0,0.062102,0
117315,18300.0,12500.0,0.221582,0
21978,17441.0,14770.0,0.354072,0
124533,13930.0,NaN,4902.000000,0
72592,13498.0,4800.0,0.347428,0
71705,13400.0,5000.0,0.995801,0

In [58]:
data_dict = pd.read_excel(
    "../data/raw/Data Dictionary.xls",
    engine="xlrd"
)

data_dict

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,Variable Name,Description,Type
1,SeriousDlqin2yrs,Person experienced 90 days past due delinquenc...,Y/N
2,RevolvingUtilizationOfUnsecuredLines,Total balance on credit cards and personal lin...,percentage
3,age,Age of borrower in years,integer
4,NumberOfTime30-59DaysPastDueNotWorse,Number of times borrower has been 30-59 days p...,integer
5,DebtRatio,"Monthly debt payments, alimony,living costs di...",percentage
6,MonthlyIncome,Monthly income,real
7,NumberOfOpenCreditLinesAndLoans,Number of Open loans (installment like car loa...,integer
8,NumberOfTimes90DaysLate,Number of times borrower has been 90 days or m...,integer
9,NumberRealEstateLoansOrLines,Number of mortgage and real estate loans inclu...,integer
10,NumberOfTime60-89DaysPastDueNotWorse,Number of times borrower has been 60-89 days p...,integer
11,NumberOfDependents,Number of dependents in family excluding thems...,integer

In [59]:
df.groupby(TARGET).median(numeric_only=True).T

SeriousDlqin2yrs                                 0             1
Unnamed: 0                            74982.500000  75283.000000
RevolvingUtilizationOfUnsecuredLines      0.133288      0.838853
age                                      52.000000     45.000000
NumberOfTime30-59DaysPastDueNotWorse      0.000000      0.000000
DebtRatio                                 0.362659      0.428227
MonthlyIncome                          5466.000000   4500.000000
NumberOfOpenCreditLinesAndLoans           8.000000      7.000000
NumberOfTimes90DaysLate                   0.000000      0.000000
NumberRealEstateLoansOrLines              1.000000      1.000000
NumberOfTime60-89DaysPastDueNotWorse      0.000000      0.000000
NumberOfDependents                        0.000000      0.000000

In [61]:
delinquency_cols = [
    "NumberOfTime30-59DaysPastDueNotWorse",
    "NumberOfTime60-89DaysPastDueNotWorse",
    "NumberOfTimes90DaysLate"
]

for col in delinquency_cols:
    result = df.groupby(TARGET)[col].apply(lambda x: (x > 0).mean() * 100)
    print(f"\n{col}")
    print(result)

NumberOfTime30-59DaysPastDueNotWorse
SeriousDlqin2yrs
0    13.571806
1    49.720726
Name: NumberOfTime30-59DaysPastDueNotWorse, dtype: float64

NumberOfTime60-89DaysPastDueNotWorse
SeriousDlqin2yrs
0     3.453499
1    27.628167
Name: NumberOfTime60-89DaysPastDueNotWorse, dtype: float64

NumberOfTimes90DaysLate
SeriousDlqin2yrs
0     3.476360
1    34.629962
Name: NumberOfTimes90DaysLate, dtype: float64

In [62]:
# 2. Mean comparison
df.groupby(TARGET).mean(numeric_only=True).T

SeriousDlqin2yrs                                 0             1
Unnamed: 0                            74968.042429  75453.643427
RevolvingUtilizationOfUnsecuredLines      6.168855      4.367282
age                                      52.751375     45.926591
NumberOfTime30-59DaysPastDueNotWorse      0.280109      2.388490
DebtRatio                               357.151168    295.121066
MonthlyIncome                          6747.837774   5630.826493
NumberOfOpenCreditLinesAndLoans           8.493620      7.882306
NumberOfTimes90DaysLate                   0.135225      2.091362
NumberRealEstateLoansOrLines              1.020368      0.988530
NumberOfTime60-89DaysPastDueNotWorse      0.126666      1.828047
NumberOfDependents                        0.743417      0.948208

In [63]:
for col in delinquency_cols:
    print(f"\n{col}")
    print(
        df[col]
        .value_counts()
        .sort_index()
        .tail(10)
    )

NumberOfTime30-59DaysPastDueNotWorse
NumberOfTime30-59DaysPastDueNotWorse
6     140
7      54
8      25
9      12
10      4
11      1
12      2
13      1
96      5
98    264
Name: count, dtype: int64

NumberOfTime60-89DaysPastDueNotWorse
NumberOfTime60-89DaysPastDueNotWorse
3     318
4     105
5      34
6      16
7       9
8       2
9       1
11      1
96      5
98    264
Name: count, dtype: int64

NumberOfTimes90DaysLate
NumberOfTimes90DaysLate
9      19
10      8
11      5
12      2
13      4
14      2
15      2
17      1
96      5
98    264
Name: count, dtype: int64

In [64]:
for col in delinquency_cols:
    print(
        col,
        "96 =", (df[col] == 96).sum(),
        "98 =", (df[col] == 98).sum()
    )

NumberOfTime30-59DaysPastDueNotWorse 96 = 5 98 = 264
NumberOfTime60-89DaysPastDueNotWorse 96 = 5 98 = 264
NumberOfTimes90DaysLate 96 = 5 98 = 264

In [65]:
mask_96_98 = (
    df[delinquency_cols]
    .isin([96, 98])
    .any(axis=1)
)

mask_96_98.sum()

np.int64(269)

In [66]:
all_three_anomalous = (
    df[delinquency_cols]
    .isin([96, 98])
    .all(axis=1)
)

all_three_anomalous.sum()

np.int64(269)

In [67]:
df.loc[all_three_anomalous, TARGET].value_counts(normalize=True) * 100

SeriousDlqin2yrs
1    54.64684
0    45.35316
Name: proportion, dtype: float64

In [69]:
df.loc[
    all_three_anomalous,
    delinquency_cols
].value_counts()

NumberOfTime30-59DaysPastDueNotWorse  NumberOfTime60-89DaysPastDueNotWorse  NumberOfTimes90DaysLate
98                                    98                                    98                         264
96                                    96                                    96                           5
Name: count, dtype: int64

In [70]:
anomalous_df = df.loc[all_three_anomalous].copy()

anomalous_df.groupby(
    delinquency_cols[0]
)[TARGET].agg(
    ["count", "mean"]
)

                                      count      mean
NumberOfTime30-59DaysPastDueNotWorse
96                                        5  0.800000
98                                      264  0.541667

In [71]:
anomalous_df["MonthlyIncome"].isna().sum()

np.int64(121)

In [72]:
anomalous_df["MonthlyIncome"].describe()

count      148.000000
mean      2557.135135
std       2745.777653
min          0.000000
25%       1333.000000
50%       2168.500000
75%       3174.500000
max      28733.000000
Name: MonthlyIncome, dtype: float64

In [73]:
for value in [96, 98]:
    subset = anomalous_df[
        anomalous_df["NumberOfTime30-59DaysPastDueNotWorse"] == value
    ]

    print(f"\nValue = {value}")
    print("Rows:", len(subset))
    print("Missing income:", subset["MonthlyIncome"].isna().sum())
    print("Missing income %:", subset["MonthlyIncome"].isna().mean() * 100)

Value = 96
Rows: 5
Missing income: 1
Missing income %: 20.0

Value = 98
Rows: 264
Missing income: 120
Missing income %: 45.45454545454545

In [74]:
df_clean = df.copy()

In [75]:
df_clean = df_clean.drop(columns=["Unnamed: 0"])

In [76]:
df_clean = df_clean.drop(columns=["Unnamed: 0"])

KeyError: "['Unnamed: 0'] not found in axis"

In [77]:
df_clean.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='str')

In [78]:
delinquency_cols = [
    "NumberOfTime30-59DaysPastDueNotWorse",
    "NumberOfTime60-89DaysPastDueNotWorse",
    "NumberOfTimes90DaysLate"
]

df_clean["DelinquencyAnomaly"] = (
    df_clean[delinquency_cols]
    .isin([96, 98])
    .any(axis=1)
    .astype(int)
)

In [79]:
df_clean[delinquency_cols] = (
    df_clean[delinquency_cols]
    .replace([96, 98], np.nan)
)

In [80]:
df_clean[delinquency_cols] = (
    df_clean[delinquency_cols]
    .replace([96, 98], np.nan)
)

In [81]:
df_clean.loc[df_clean["age"] == 0, "age"] = np.nan

In [82]:
df_clean.isnull().sum().sort_values(ascending=False)

MonthlyIncome                           29731
NumberOfDependents                       3924
NumberOfTime30-59DaysPastDueNotWorse      269
NumberOfTime60-89DaysPastDueNotWorse      269
NumberOfTimes90DaysLate                   269
age                                         1
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
NumberOfOpenCreditLinesAndLoans             0
DebtRatio                                   0
NumberRealEstateLoansOrLines                0
DelinquencyAnomaly                          0
dtype: int64

In [84]:
df_clean["DelinquencyAnomaly"].value_counts()

DelinquencyAnomaly
0    149731
1       269
Name: count, dtype: int64

In [85]:
df_clean.shape

(150000, 12)

In [86]:
df_clean.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,DelinquencyAnomaly
0,1,0.766127,45.0,2.0,0.802982,9120.0,13,0.0,6,0.0,2.0,0
1,0,0.957151,40.0,0.0,0.121876,2600.0,4,0.0,0,0.0,1.0,0
2,0,0.658180,38.0,1.0,0.085113,3042.0,2,1.0,0,0.0,0.0,0
3,0,0.233810,30.0,0.0,0.036050,3300.0,5,0.0,0,0.0,0.0,0
4,0,0.907239,49.0,1.0,0.024926,63588.0,7,0.0,1,0.0,0.0,0

In [87]:
df_clean[delinquency_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
NumberOfTime30-59DaysPastDueNotWorse,149731.0,0.245794,0.697780,0.0,0.0,0.0,0.0,13.0
NumberOfTime60-89DaysPastDueNotWorse,149731.0,0.064823,0.330073,0.0,0.0,0.0,0.0,11.0
NumberOfTimes90DaysLate,149731.0,0.090456,0.485527,0.0,0.0,0.0,0.0,17.0

In [88]:
df_clean[delinquency_cols].isna().sum()

NumberOfTime30-59DaysPastDueNotWorse    269
NumberOfTime60-89DaysPastDueNotWorse    269
NumberOfTimes90DaysLate                 269
dtype: int64

In [89]:
df_clean["IncomeMissing"] = df_clean["MonthlyIncome"].isna().astype(int)

In [90]:
df_clean.groupby("IncomeMissing")[
    ["DebtRatio", "RevolvingUtilizationOfUnsecuredLines"]
].median()

                 DebtRatio  RevolvingUtilizationOfUnsecuredLines
IncomeMissing
0                 0.296023                              0.177282
1              1159.000000                              0.081697

In [91]:
df_clean.groupby("IncomeMissing")[
    ["DebtRatio", "RevolvingUtilizationOfUnsecuredLines"]
].mean()

                 DebtRatio  RevolvingUtilizationOfUnsecuredLines
IncomeMissing
0                26.598777                              5.899873
1              1673.396556                              6.649421

In [92]:
df_clean.groupby("IncomeMissing")[
    "DebtRatio"
].quantile([0.50, 0.90, 0.99, 0.999])

IncomeMissing
0              0.500        0.296023
               0.900        0.763149
               0.990      661.820000
               0.999     4323.588000
1              0.500     1159.000000
               0.900     3785.000000
               0.990     8084.500000
               0.999    21388.430000
Name: DebtRatio, dtype: float64

In [93]:
df_clean.groupby("IncomeMissing")[
    "RevolvingUtilizationOfUnsecuredLines"
].quantile([0.50, 0.90, 0.99, 0.999])

IncomeMissing
0              0.500       0.177282
               0.900       0.972610
               0.990       1.089958
               0.999    1131.476000
1              0.500       0.081697
               0.900       1.000000
               0.990       1.113603
               0.999    1970.510000
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [94]:
df_clean.groupby("IncomeMissing")[TARGET].mean() * 100

IncomeMissing
0    6.948590
1    5.613669
Name: SeriousDlqin2yrs, dtype: float64

In [96]:
df_clean.groupby("IncomeMissing")["MonthlyIncome"].count()

IncomeMissing
0    120269
1         0
Name: MonthlyIncome, dtype: int64

In [97]:
test_df = pd.read_csv("../data/raw/cs-test.csv")

print(test_df.shape)
print(test_df.columns.tolist())
print("Target present:", TARGET in test_df.columns)

(101503, 12)
['Unnamed: 0', 'SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents']
Target present: True

In [98]:
test_df[TARGET].value_counts(dropna=False)

SeriousDlqin2yrs
NaN    101503
Name: count, dtype: int64

In [99]:
test_df[TARGET].nunique()

0

In [100]:
print("Training columns:")
print(df.columns.tolist())

print("\nTest columns:")
print(test_df.columns.tolist())

Training columns:
['Unnamed: 0', 'SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents']

Test columns:
['Unnamed: 0', 'SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents']

In [101]:
print(
    "Same columns:",
    list(df.columns) == list(test_df.columns)
)

Same columns: True